os: osx
language: objective-c
osx_image: xcode11.2
script:
  - set -o pipefail && xcodebuild build -project RPSGame.xcodeproj -scheme RPSGame -sdk iphonesimulator13.0 -destination 'name=iPhone 6,OS=12.4' ONLY_ACTIVE_ARCH=NO | xcpretty
